export default {
  identifier: 'anto.tools',
  width: 48,
  height: 700,
  alwaysOnTop: true,
  minimizable: false,
  maximizable: false,
  fullscreenable: false,
  closable: false,
  titleBarStyle: 'hidden',
  vibrancy: 'sidebar',
  resizable: false,
  show: false,
  frame: false,
  transparent: true,
};
